name: Release

on:
  release:
    types: [published, edited]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: lets publish
      run: |
        echo "::set-env name=TAG::$(echo $GITHUB_REF | sed 's|.*\/||')"
        echo $TAG
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
